export const DEFAULT_CATALOG_MAX_RESPONSE_BYTES = 5 * 1024 * 1024;
export const DEFAULT_CATALOG_REQUEST_TIMEOUT_MS = 30_000;
export const DEFAULT_CATALOG_MAX_MODELS = 2_000;
export const DEFAULT_CATALOG_MAX_OBSERVATIONS = 10_000;
export const DEFAULT_CATALOG_MAX_OBSERVATIONS_PER_MODEL = 1_000;
export const DEFAULT_CATALOG_MAX_ENTRIES_PER_OBSERVATION = 100;

export const MAX_CATALOG_STATE_BYTES = 64 * 1024;
export const MAX_CATALOG_ETAG_BYTES = 8 * 1024;
